name: untitled5
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.0
  qr_flutter: ^4.1.0
  intl: ^0.18.0
  google_mlkit_face_detection: ^0.10.0


  font_awesome_flutter: ^10.1.0
  image_picker: ^1.0.0
  image_picker_for_web: ^3.0.0
  http: ^1.2.0
  camera: ^0.10.5+5
  sqflite: ^2.2.5+1
  path_provider: ^2.0.14
  path: ^1.8.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
